{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNhiVN8DOuLwkLq5QWLfj8T",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/JKTajo/20250714_count_TAX/blob/main/freetax.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import io\n",
        "\n",
        "def process_ecount_file(df: pd.DataFrame) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    이카운트 엑셀 파일을 홈택스 업로드 양식으로 변환합니다.\n",
        "\n",
        "    Args:\n",
        "        df (pd.DataFrame): 원본 이카운트 데이터프레임.\n",
        "\n",
        "    Returns:\n",
        "        pd.DataFrame: 변환된 홈택스 양식의 데이터프레임.\n",
        "    \"\"\"\n",
        "    # 1. 데이터 전처리\n",
        "    df['code'] = '01'  # 유형: 01 (일반세금계산서)\n",
        "    df['Date'] = df['Date'].astype(str).str[:8]\n",
        "    df['day'] = df['Date'].str[-2:]\n",
        "    df['TaxNo_Send'] = df['TaxNo_Send'].astype(str)\n",
        "    df['TaxNo_get'] = df['TaxNo_get'].astype(str)\n",
        "\n",
        "    # 2. 공급가액이 0보다 큰 데이터만 선택 및 품목별 분리\n",
        "    df = df[df['price'] > 0]\n",
        "\n",
        "    # '하나은행' 데이터 별도 처리\n",
        "    df_Hana = df[df['TaxNo_get'] == '2298500670']\n",
        "    df = df[df['TaxNo_get'] != '2298500670']\n",
        "\n",
        "    # 품목별 DataFrame 생성\n",
        "    df1 = df[df['item'] == '임대료']\n",
        "    df2 = df[df['item'] == '관리비']\n",
        "    df3 = df[df['item'] == '전기료']\n",
        "    df4 = df[df['item'] == '주차료']\n",
        "\n",
        "    # 분리했던 '하나은행' 데이터를 '임대료'에 다시 포함\n",
        "    if not df_Hana.empty:\n",
        "        df1 = pd.concat([df_Hana, df1])\n",
        "\n",
        "    # 3. 데이터 병합\n",
        "    # 기준이 되는 키 컬럼 정의\n",
        "    key_id = ['code', 'Date', 'TaxNo_Send', 'J1', 'Title_send', 'Name_send',\n",
        "              'Addr_send', 'sub1', 'sub2', 'Email_send',\n",
        "              'TaxNo_get', 'J2', 'TaxTitle_get', 'Name_get',\n",
        "              'Addr_get', 'type1', 'type2', 'Email_get', 'Email2_get', 'note_Sum']\n",
        "\n",
        "    # 품목별 데이터를 key_id 기준으로 병합\n",
        "    merged_df = pd.merge(df1, df2, how='outer', on=key_id, suffixes=('_1', '_2'))\n",
        "    merged_df = pd.merge(merged_df, df3, how='outer', on=key_id)\n",
        "    merged_df = pd.merge(merged_df, df4, how='outer', on=key_id, suffixes=('_3', '_4'))\n",
        "\n",
        "    # 4. 합계 계산 및 추가\n",
        "    price_cols = ['price_1', 'price_2', 'price_3', 'price_4']\n",
        "    vat_cols = ['VAT_1', 'VAT_2', 'VAT_3', 'VAT_4']\n",
        "\n",
        "    # DataFrame에 해당 열이 없을 경우 0으로 생성\n",
        "    for col in price_cols + vat_cols:\n",
        "        if col not in merged_df.columns:\n",
        "            merged_df[col] = 0\n",
        "\n",
        "    # NaN 값을 0으로 채우고 합계 계산\n",
        "    merged_df.loc[:, 'price_sum'] = merged_df[price_cols].fillna(0).sum(axis=1).astype(int)\n",
        "    merged_df.loc[:, 'VAT_sum'] = merged_df[vat_cols].fillna(0).sum(axis=1).astype(int)\n",
        "\n",
        "    # 5. 홈택스 양식에 맞게 열 순서 재정렬 및 추가\n",
        "    # 최종적으로 필요한 열 목록\n",
        "    final_columns = [\n",
        "        'code', 'Date', 'TaxNo_Send', 'J1', 'Title_send', 'Name_send', 'Addr_send',\n",
        "        'sub1', 'sub2', 'Email_send', 'TaxNo_get', 'J2', 'TaxTitle_get', 'Name_get',\n",
        "        'Addr_get', 'type1', 'type2', 'Email_get', 'Email2_get', 'price_sum',\n",
        "        'VAT_sum', 'note_Sum', 'day_1', 'item_1', 'standard_1', 'quantity_1',\n",
        "        'unit_price_1', 'price_1', 'VAT_1', 'note_1', 'day_2', 'item_2',\n",
        "        'standard_2', 'quantity_2', 'unit_price_2', 'price_2', 'VAT_2', 'note_2',\n",
        "        'day_3', 'item_3', 'standard_3', 'quantity_3', 'unit_price_3', 'price_3',\n",
        "        'VAT_3', 'note_3', 'day_4', 'item_4', 'standard_4', 'quantity_4',\n",
        "        'unit_price_4', 'price_4', 'VAT_4', 'note_4'\n",
        "    ]\n",
        "\n",
        "    # 없는 열은 빈 값으로 추가\n",
        "    for col in final_columns:\n",
        "        if col not in merged_df.columns:\n",
        "            merged_df[col] = ''\n",
        "\n",
        "    df_final = merged_df[final_columns]\n",
        "\n",
        "    # 6. 추가 데이터 정리\n",
        "    for i in range(1, 5):\n",
        "        df_final.loc[:, f'note_{i}'] = ''\n",
        "\n",
        "    df_final.loc[:, \"etc1\"] = \"\"\n",
        "    df_final.loc[:, \"etc2\"] = \"\"\n",
        "    df_final.loc[:, \"etc3\"] = \"\"\n",
        "    df_final.loc[:, \"etc4\"] = \"\"\n",
        "    df_final.loc[:, \"etc5\"] = \"02\"  # 청구(02)\n",
        "\n",
        "    df_final.loc[:, 'TaxNo_get'] = df_final['TaxNo_get'].str.replace('_B', '', regex=False)\n",
        "\n",
        "    # NaN 값을 빈 문자열로 변환\n",
        "    df_final = df_final.fillna('')\n",
        "\n",
        "    return df_final\n"
      ],
      "metadata": {
        "id": "tEiEuAdv4tX5"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def process_freetax_file(df: pd.DataFrame) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    이카운트 엑셀 파일을 홈택스 업로드 양식으로 변환합니다.\n",
        "\n",
        "    Args:\n",
        "        df (pd.DataFrame): 원본 이카운트 데이터프레임.\n",
        "\n",
        "    Returns:\n",
        "        pd.DataFrame: 변환된 홈택스 양식의 데이터프레임.\n",
        "    \"\"\"\n",
        "    # 1. 데이터 전처리\n",
        "    df['code'] = '02'  # 유형: 02 (일반계산서)\n",
        "    df['Date'] = df['Date'].astype(str).str[:8]\n",
        "    df['day'] = df['Date'].str[-2:]\n",
        "    df['TaxNo_Send'] = df['TaxNo_Send'].astype(str)\n",
        "    df['TaxNo_get'] = df['TaxNo_get'].astype(str)\n",
        "\n",
        "    # 2. 공급가액이 0보다 큰 데이터만 선택 및 품목별 분리\n",
        "    df = df[df['price'] > 0]\n",
        "\n",
        "    # '하나은행' 데이터 별도 처리\n",
        "    df_Hana = df[df['TaxNo_get'] == '2298500670']\n",
        "    df = df[df['TaxNo_get'] != '2298500670']\n",
        "\n",
        "    # 품목별 DataFrame 생성\n",
        "    df1 = df[df['item'] == '수도료']\n",
        "\n",
        "    # 분리했던 '하나은행' 데이터를 '수도료'에 다시 포함\n",
        "    if not df_Hana.empty:\n",
        "        df1 = pd.concat([df_Hana, df1])\n",
        "\n",
        "    # 3. 데이터 병합\n",
        "    # 기준이 되는 키 컬럼 정의\n",
        "    key_id = ['code', 'Date', 'TaxNo_Send', 'J1', 'Title_send', 'Name_send',\n",
        "              'Addr_send', 'sub1', 'sub2', 'Email_send',\n",
        "              'TaxNo_get', 'J2', 'TaxTitle_get', 'Name_get',\n",
        "              'Addr_get', 'type1', 'type2', 'Email_get', 'Email2_get', 'note_Sum']\n",
        "\n",
        "    # 품목별 데이터를 key_id 기준으로 병합\n",
        "    #merged_df = pd.merge(df1, df2, how='outer', on=key_id, suffixes=('_1', '_2'))\n",
        "    #merged_df = pd.merge(merged_df, df3, how='outer', on=key_id)\n",
        "    #merged_df = pd.merge(merged_df, df4, how='outer', on=key_id, suffixes=('_3', '_4'))\n",
        "\n",
        "    # 4. 합계 계산 및 추가\n",
        "    price_cols = ['price_1', 'price_2', 'price_3', 'price_4']\n",
        "    vat_cols = ['VAT_1', 'VAT_2', 'VAT_3', 'VAT_4']\n",
        "\n",
        "    # DataFrame에 해당 열이 없을 경우 0으로 생성\n",
        "    for col in price_cols + vat_cols:\n",
        "        if col not in df.columns:\n",
        "            df[col] = 0\n",
        "\n",
        "    # NaN 값을 0으로 채우고 합계 계산\n",
        "    df.loc[:, 'price_sum'] = df[price_cols].fillna(0).sum(axis=1).astype(int)\n",
        "    df.loc[:, 'VAT_sum'] = df[vat_cols].fillna(0).sum(axis=1).astype(int)\n",
        "\n",
        "    # 5. 홈택스 양식에 맞게 열 순서 재정렬 및 추가\n",
        "    # 최종적으로 필요한 열 목록\n",
        "    final_columns = [\n",
        "        'code', 'Date', 'TaxNo_Send', 'J1', 'Title_send', 'Name_send', 'Addr_send',\n",
        "        'sub1', 'sub2', 'Email_send', 'TaxNo_get', 'J2', 'TaxTitle_get', 'Name_get',\n",
        "        'Addr_get', 'type1', 'type2', 'Email_get', 'Email2_get', 'price_sum',\n",
        "        'VAT_sum', 'note_Sum', 'day_1', 'item_1', 'standard_1', 'quantity_1',\n",
        "        'unit_price_1', 'price_1', 'VAT_1', 'note_1', 'day_2', 'item_2',\n",
        "        'standard_2', 'quantity_2', 'unit_price_2', 'price_2', 'VAT_2', 'note_2',\n",
        "        'day_3', 'item_3', 'standard_3', 'quantity_3', 'unit_price_3', 'price_3',\n",
        "        'VAT_3', 'note_3', 'day_4', 'item_4', 'standard_4', 'quantity_4',\n",
        "        'unit_price_4', 'price_4', 'VAT_4', 'note_4'\n",
        "    ]\n",
        "\n",
        "    # 없는 열은 빈 값으로 추가\n",
        "    for col in final_columns:\n",
        "        if col not in df.columns:\n",
        "            df[col] = ''\n",
        "\n",
        "    df_final = df[final_columns]\n",
        "\n",
        "    # 6. 추가 데이터 정리\n",
        "    for i in range(1, 5):\n",
        "        df_final.loc[:, f'note_{i}'] = ''\n",
        "\n",
        "    df_final.loc[:, \"etc1\"] = \"\"\n",
        "    df_final.loc[:, \"etc2\"] = \"\"\n",
        "    df_final.loc[:, \"etc3\"] = \"\"\n",
        "    df_final.loc[:, \"etc4\"] = \"\"\n",
        "    df_final.loc[:, \"etc5\"] = \"02\"  # 청구(02)\n",
        "\n",
        "    df_final.loc[:, 'TaxNo_get'] = df_final['TaxNo_get'].str.replace('_B', '', regex=False)\n",
        "\n",
        "    # NaN 값을 빈 문자열로 변환\n",
        "    df_final = df_final.fillna('')\n",
        "\n",
        "    return df_final\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "# --- Streamlit App UI ---\n",
        "st.set_page_config(page_title=\"홈택스 통합 변환기\", layout=\"wide\")\n",
        "st.title(\"📄 이카운트 엑셀 → 홈택스 변환기\")\n",
        "st.info(\"이카운트 '판매현황' 파일을 홈택스 [세금계산서] 또는 [면세 계산서] 양식으로 변환합니다.\")\n",
        "\n",
        "# 1. 변환 모드 선택 (라디오 버튼 추가)\n",
        "mode = st.radio(\n",
        "    \"변환할 양식을 선택하세요:\",\n",
        "    (\"과세(세금계산서)\", \"면세(계산서)\"),\n",
        "    horizontal=True\n",
        ")\n",
        "\n",
        "uploaded_file = st.file_uploader(\"📂 이카운트 엑셀 파일을 업로드하세요\", type=[\"xlsx\", \"xls\"])\n",
        "\n",
        "if uploaded_file:\n",
        "    st.success(f\"파일 업로드 완료: **{uploaded_file.name}**\")\n",
        "\n",
        "    try:\n",
        "        # 엑셀 로드 (이카운트 양식 특성 반영)\n",
        "        df_original = pd.read_excel(uploaded_file, skiprows=1, skipfooter=2)\n",
        "\n",
        "        with st.expander(\"📂 원본 데이터 확인\"):\n",
        "            st.dataframe(df_original)\n",
        "\n",
        "        if st.button(\"🚀 변환 실행\", use_container_width=True):\n",
        "            with st.spinner('양식을 생성 중입니다...'):\n",
        "                # 변환 로직 (선택 모드에 따라 처리)\n",
        "                if mode == \"과세(세금계산서)\":\n",
        "                    processed_df = process_ecount_file(df_original.copy())\n",
        "                elif mode == \"면세(계산서)\":\n",
        "                    processed_df = process_freetax_file(df_original.copy())\n",
        "                else:\n",
        "                    st.error(\"유효하지 않은 변환 모드입니다.\")\n",
        "                    st.stop()\n",
        "\n",
        "                st.subheader(f\"✅ {mode} 변환 결과\")\n",
        "                st.dataframe(processed_df)\n",
        "\n",
        "                # 파일 저장 설정\n",
        "                output = io.BytesIO()\n",
        "\n",
        "                # 모드별 파일명 및 시트명 분기\n",
        "                if mode == \"면세(계산서)\":\n",
        "                    file_name = \"freetax_upload.xlsx\"\n",
        "                    sheet_name = \"free_sale\"  # 홈택스 면세 양식 시트명 (예시)\n",
        "                else:\n",
        "                    file_name = \"tax_upload.xlsx\"\n",
        "                    sheet_name = \"sale1\"\n",
        "\n",
        "                with pd.ExcelWriter(output, engine='openpyxl') as writer:\n",
        "                    # 홈택스 일괄업로드 양식은 6행(startrow=5)부터 데이터 시작\n",
        "                    processed_df.to_excel(writer, sheet_name=sheet_name, index=False, startrow=5)\n",
        "\n",
        "                excel_data = output.getvalue()\n",
        "\n",
        "                st.download_button(\n",
        "                    label=f\"📥 '{file_name}' 다운로드\",\n",
        "                    data=excel_data,\n",
        "                    file_name=file_name,\n",
        "                    mime=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\",\n",
        "                    use_container_width=True\n",
        "                )\n",
        "\n",
        "    except Exception as e:\n",
        "        st.error(f\"오류 발생: {e}\")"
      ],
      "metadata": {
        "id": "Pho_YqK55DcK"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}