{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOvJAr9B3wSFGAw/4B2A4nh",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/JKTajo/20250714_count_TAX/blob/main/tax_ai.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "pip install streamlit pandas openpyxl"
      ],
      "metadata": {
        "id": "TDZiZeOH9wMS"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "Mo5FqDwA9Mam"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import io\n",
        "\n",
        "# --- 1. 데이터 변환 핵심 로직 함수 ---\n",
        "def process_ecount_file(df: pd.DataFrame, is_free_tax: bool = False) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    이카운트 데이터를 홈택스 과세/면세 양식으로 변환합니다.\n",
        "    \"\"\"\n",
        "    # 기초 전처리\n",
        "    df['code'] = '02' if is_free_tax else '01'  # 01:과세, 02:면세\n",
        "    df['Date'] = df['Date'].astype(str).str[:8]\n",
        "    df['day'] = df['Date'].str[-2:]\n",
        "    df['TaxNo_Send'] = df['TaxNo_Send'].astype(str)\n",
        "    df['TaxNo_get'] = df['TaxNo_get'].astype(str)\n",
        "\n",
        "    # 공급가액이 0보다 큰 데이터만 필터링\n",
        "    df = df[df['price'] > 0]\n",
        "\n",
        "    # 홈택스 표준 컬럼 정의 (총 54개 내외)\n",
        "    key_id = ['code', 'Date', 'TaxNo_Send', 'J1', 'Title_send', 'Name_send',\n",
        "              'Addr_send', 'sub1', 'sub2', 'Email_send',\n",
        "              'TaxNo_get', 'J2', 'TaxTitle_get', 'Name_get',\n",
        "              'Addr_get', 'type1', 'type2', 'Email_get', 'Email2_get', 'note_Sum']\n",
        "\n",
        "    if is_free_tax:\n",
        "        # --- [면세: 수도료 전용 로직] ---\n",
        "        # 수도료 항목만 추출\n",
        "        merged_df = df[df['item'] == '수도료'].copy()\n",
        "\n",
        "        # 합계 계산 (면세이므로 VAT는 0)\n",
        "        merged_df['price_sum'] = merged_df['price'].fillna(0).astype(int)\n",
        "        merged_df['VAT_sum'] = 0\n",
        "\n",
        "        # 품목 1번 위치에 수도료 데이터 매핑\n",
        "        merged_df['day_1'] = merged_df['day']\n",
        "        merged_df['item_1'] = merged_df['item']\n",
        "        merged_df['price_1'] = merged_df['price']\n",
        "        merged_df['VAT_1'] = 0\n",
        "\n",
        "    else:\n",
        "        # --- [과세: 임대료/관리비/전기료/주차료 병합 로직] ---\n",
        "        # 하나은행 별도 처리 (특정 사업자번호)\n",
        "        df_Hana = df[df['TaxNo_get'] == '2298500670']\n",
        "        df_others = df[df['TaxNo_get'] != '2298500670']\n",
        "\n",
        "        # 품목별 분리 (과세 항목)\n",
        "        df1 = df_others[df_others['item'] == '임대료']\n",
        "        df2 = df_others[df_others['item'] == '관리비']\n",
        "        df3 = df_others[df_others['item'] == '전기료']\n",
        "        df4 = df_others[df_others['item'] == '주차료']\n",
        "\n",
        "        # 하나은행은 임대료(df1)에 병합\n",
        "        if not df_Hana.empty:\n",
        "            df1 = pd.concat([df_Hana, df1])\n",
        "\n",
        "        # 가로로 병합 (거래처 키 기준)\n",
        "        merged_df = pd.merge(df1, df2, how='outer', on=key_id, suffixes=('_1', '_2'))\n",
        "        merged_df = pd.merge(merged_df, df3, how='outer', on=key_id)\n",
        "        merged_df = pd.merge(merged_df, df4, how='outer', on=key_id, suffixes=('_3', '_4'))\n",
        "\n",
        "        # 합계 계산\n",
        "        price_cols = ['price_1', 'price_2', 'price_3', 'price_4']\n",
        "        vat_cols = ['VAT_1', 'VAT_2', 'VAT_3', 'VAT_4']\n",
        "\n",
        "        for col in price_cols + vat_cols:\n",
        "            if col not in merged_df.columns:\n",
        "                merged_df[col] = 0\n",
        "\n",
        "        merged_df['price_sum'] = merged_df[price_cols].fillna(0).sum(axis=1).astype(int)\n",
        "        merged_df['VAT_sum'] = merged_df[vat_cols].fillna(0).sum(axis=1).astype(int)\n",
        "\n",
        "    # 최종 결과 프레임 구성 (홈택스 표준 순서)\n",
        "    final_columns = [\n",
        "        'code', 'Date', 'TaxNo_Send', 'J1', 'Title_send', 'Name_send', 'Addr_send',\n",
        "        'sub1', 'sub2', 'Email_send', 'TaxNo_get', 'J2', 'TaxTitle_get', 'Name_get',\n",
        "        'Addr_get', 'type1', 'type2', 'Email_get', 'Email2_get', 'price_sum',\n",
        "        'VAT_sum', 'note_Sum', 'day_1', 'item_1', 'standard_1', 'quantity_1',\n",
        "        'unit_price_1', 'price_1', 'VAT_1', 'note_1', 'day_2', 'item_2',\n",
        "        'standard_2', 'quantity_2', 'unit_price_2', 'price_2', 'VAT_2', 'note_2',\n",
        "        'day_3', 'item_3', 'standard_3', 'quantity_3', 'unit_price_3', 'price_3',\n",
        "        'VAT_3', 'note_3', 'day_4', 'item_4', 'standard_4', 'quantity_4',\n",
        "        'unit_price_4', 'price_4', 'VAT_4', 'note_4'\n",
        "    ]\n",
        "\n",
        "    # 없는 컬럼 생성 및 빈값 처리\n",
        "    for col in final_columns:\n",
        "        if col not in merged_df.columns:\n",
        "            merged_df[col] = ''\n",
        "\n",
        "    df_final = merged_df[final_columns].copy()\n",
        "\n",
        "    # 추가 필드 설정\n",
        "    df_final[\"etc5\"] = \"02\"  # 영수(01)/청구(02) 중 청구로 고정\n",
        "    df_final['TaxNo_get'] = df_final['TaxNo_get'].str.replace('_B', '', regex=False)\n",
        "\n",
        "    return df_final.fillna('')\n",
        "\n",
        "# --- 2. Streamlit UI 부분 ---\n",
        "st.set_page_config(page_title=\"홈택스 세금계산서 변환기\", layout=\"wide\")\n",
        "st.title(\"📄 이카운트 엑셀 → 홈택스 업로드 양식 변환기\")\n",
        "\n",
        "# 변환 타입 선택\n",
        "mode = st.radio(\"변환 유형을 선택하세요\", [\"과세(세금계산서)\", \"면세(수도료 계산서)\"], horizontal=True)\n",
        "is_free = (mode == \"면세(수도료 계산서)\")\n",
        "\n",
        "st.info(f\"현재 선택된 모드: **{mode}**\")\n",
        "\n",
        "uploaded_file = st.file_uploader(\"📂 이카운트 엑셀 파일을 업로드하세요\", type=[\"xlsx\", \"xls\"])\n",
        "\n",
        "if uploaded_file:\n",
        "    try:\n",
        "        # 엑셀 로드 (이카운트 기본 양식에 맞춰 상단 1행 제외, 하단 합계 2행 제외)\n",
        "        df_original = pd.read_excel(uploaded_file, skiprows=1, skipfooter=2, header=0)\n",
        "\n",
        "        with st.expander(\"📂 업로드된 원본 데이터 미리보기\"):\n",
        "            st.dataframe(df_original)\n",
        "\n",
        "        if st.button(\"🚀 변환 실행 및 파일 생성\", use_container_width=True):\n",
        "            with st.spinner('데이터를 변환 중입니다...'):\n",
        "                processed_df = process_ecount_file(df_original.copy(), is_free_tax=is_free)\n",
        "\n",
        "                st.subheader(f\"✅ {mode} 결과 미리보기\")\n",
        "                st.dataframe(processed_df)\n",
        "\n",
        "                # 파일명 및 홈택스 시트명 설정\n",
        "                # 홈택스는 시트 이름이 다르면 인식을 못할 수 있으므로 주의\n",
        "                final_filename = \"freetax_upload.xlsx\" if is_free else \"tax_upload.xlsx\"\n",
        "                sheet_name = \"free_sale\" if is_free else \"sale1\"\n",
        "\n",
        "                # 엑셀 파일 생성\n",
        "                output = io.BytesIO()\n",
        "                with pd.ExcelWriter(output, engine='openpyxl') as writer:\n",
        "                    # 홈택스 일괄업로드 양식은 6행(index 5)부터 데이터가 들어감\n",
        "                    processed_df.to_excel(writer, sheet_name=sheet_name, index=False, startrow=5)\n",
        "\n",
        "                excel_data = output.getvalue()\n",
        "\n",
        "                st.download_button(\n",
        "                    label=f\"📥 '{final_filename}' 다운로드\",\n",
        "                    data=excel_data,\n",
        "                    file_name=final_filename,\n",
        "                    mime=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\",\n",
        "                    use_container_width=True\n",
        "                )\n",
        "\n",
        "    except Exception as e:\n",
        "        st.error(f\"❌ 변환 중 에러가 발생했습니다: {e}\")\n",
        "        st.warning(\"이카운트 '판매현황(거래처품목별-TAX1양식)' 파일이 맞는지 확인해주세요.\")\n",
        "else:\n",
        "    st.info(\"파일을 업로드하면 변환을 시작할 수 있습니다.\")\n"
      ]
    }
  ]
}